### ISSUE TITLE
CustomerQueryRq IncludeRetElement should of type List

### ISSUE THREAD

**Issue by rashi7863** [sflagp/QBXML-Object-Models#10]
Hello Greg,

IncludeRetElement propertly should be of type List<string>. Because this may repeat. 

For reference: https://developer.intuit.com/app/developer/qbdesktop/docs/api-reference/qbdesktop/customerquery

![image](https://github.com/sflagp/QBXML-Object-Models/assets/124454921/1be523dd-e9eb-4f81-bbf9-5aa1e9b7bc06)

**Comment by sflagp** [comment]
Good morning,

This change affects all the query request inputs to be a list IncludeRetElement. Let me know if this causes any issues or is incorrect. Try this version and let me know if it works.

[QbModels.1.2.13-beta01.zip](https://github.com/sflagp/QBXML-Object-Models/files/14343500/QbModels.1.2.13-beta01.zip)

Thanks

**Comment by rashi7863** [comment]
Perfect. Thanks Greg <3
