### ISSUE TITLE
Typo in Variable name for model: InvoiceLineRetDto

### ISSUE THREAD

**Issue by rashidabbas786** [sflagp/QBXML-Object-Models#4]
Hello Grey,

I found a typo while working with invoice Line items. 

`    [XmlElement("DataExtRet")]
    public List<DataExtRetDto> DateExtRet { get; set; }`
    
    
The variable `DateExtRet` should be renamed to `DataExtRet`

Thank you <3

**Comment by sflagp** [comment]
Nice catch. I never worked with the DataExtRet fields so I don't know if they even work. 

Let me know if you find anything else. 

Have a great New Years.

[QbModels.1.2.7.zip](https://github.com/sflagp/QBXML-Object-Models/files/13792859/QbModels.1.2.7.zip)

**Comment by rashidabbas786** [comment]
Thanks <3. I'll keep you updated if anything come in future
