### ISSUE TITLE
Models are missing for ItemInventoryAssemblyQuery

### ISSUE THREAD

**Issue by rashidabbas786** [sflagp/QBXML-Object-Models#5]
Hello Greg,

Seems some models are missing in the Library. I don't see any model to make the following query and handle the response.
https://developer.intuit.com/app/developer/qbdesktop/docs/api-reference/qbdesktop/iteminventoryassemblyquery

Would be a great help if you could implement and push the release.
 
 
 Thank you

**Comment by sflagp** [comment]
Good morning Rashid,

 

Below is the test I have written for Inventory Items. I don’t have tests for the other item models but you should have the following models:

ItemDiscount

ItemFixedAsset

ItemGroup

ItemInventory

ItemNonInventory

ItemOtherCharge

ItemPayment

ItemQuery

ItemReceipt

ItemSalesTax

ItemSalesTaxGroup

ItemService

ItemSubtotal

 

Let me know if this helps.

 

Test method using ItemInventory models

        [TestMethod]

        public void TestItemInventoryModels()

        {

            using (RequestProcessor QB = new())

            {

                #region Properties

                if (QB == null)

                {

                    throw new Exception("Quickbooks not loaded or error connecting to Quickbooks.");

                }

 

                ItemInventoryRs qryRs, addRs = new(""), modRs;

                ItemInventoryAddRq addRq = new();

                ItemInventoryModRq modRq = new();

                string addRqName = $"QbProcessor";

                string result;

                #endregion

 

                #region Query Test

                ItemInventoryQueryRq qryRq = new();

                Assert.IsTrue(qryRq.IsEntityValid());

 

                qryRq.NameFilter = new() { Name = addRqName, MatchCriterion = MatchCriterion.StartsWith };

                Assert.IsTrue(qryRq.IsEntityValid());

 

                result = QB.ExecuteQbRequest(qryRq);

                qryRs = new(result);

                if (qryRs.StatusCode == "3231") Assert.Inconclusive(qryRs.StatusMessage);

                Assert.IsTrue(qryRs.StatusSeverity == "Info");

                Assert.IsTrue(string.IsNullOrEmpty(qryRs.ParseError));

                #endregion

 

                #region Add Test

                Random rdm = new();

 

                AccountQueryRq accountsRq = new() { AccountType = AccountType.Income };

                AccountRs accounts = new(QB.ExecuteQbRequest(accountsRq));

                AccountRetDto account = accounts.Accounts[rdm.Next(0, accounts.Accounts.Count)];

 

                AccountQueryRq assetsRq = new() { AccountType = AccountType.OtherAsset };

                AccountRs assets = new(QB.ExecuteQbRequest(assetsRq));

                AccountRetDto asset = assets.Accounts[rdm.Next(0, assets.Accounts.Count)];

 

                AccountQueryRq cogsRq = new() { FullName = new() { "Company COGS" }, MaxReturned = null };

                AccountRs cogss = new(QB.ExecuteQbRequest(cogsRq));

                AccountRetDto cogs = cogss.Accounts.FirstOrDefault();

 

                for (int i = 1; i <= 5; i++)

                {

                    if (!qryRs.ItemInventory.Any(item => item.ManufacturerPartNumber.Equals($"12345-0{i}")))

                    {

                        string desc = $"{addRqName}.InventoryItem_0{i}";

                        addRq = new();

                        addRq.Name = desc;

                        addRq.IsActive = true;

                        addRq.ManufacturerPartNumber = $"12345-0{i}";

                        addRq.PurchaseDesc = desc;

                        addRq.PurchaseCost = 1M;

                        addRq.SalesDesc = desc;

                        addRq.SalesPrice = 2M;

                        addRq.IncomeAccount = new() { ListID = account.ListID };

                        addRq.AssetAccount = new() { ListID = asset.ListID };

                        addRq.COGSAccount = new() { ListID = cogs.ListID };

                        Assert.IsTrue(addRq.IsEntityValid());

 

                        result = QB.ExecuteQbRequest(addRq);

                        addRs = new(result);

                        if (addRs.StatusCode == "3250") Assert.Inconclusive(addRs.StatusMessage);

                        Assert.IsTrue(addRs.StatusCode == "0");

                        Assert.IsTrue(string.IsNullOrEmpty(addRs.ParseError));

                    }

                }

                #endregion

 

                #region Mod Test

                result = QB.ExecuteQbRequest(qryRq);

                qryRs = new(result);

                foreach (ItemInventoryRetDto item in qryRs.ItemInventory)

                {

                    modRq = new();

                    modRq.ListID = item.ListID;

                    modRq.EditSequence = item.EditSequence;

                    modRq.Name = item.Name;

                    modRq.PurchaseDesc = $"{modRq.GetType().Name} updated on {DateTime.Now}";

                    modRq.PurchaseCost = 1.11M;

                    modRq.SalesPrice = 2.22M;

                    Assert.IsTrue(modRq.IsEntityValid());

 

                    result = QB.ExecuteQbRequest(modRq);

                    modRs = new(result);

                    if (modRs.StatusCode == "3250") Assert.Inconclusive(modRs.StatusMessage);

                    Assert.IsTrue(modRs.StatusCode == "0");

                    Assert.IsTrue(string.IsNullOrEmpty(modRs.ParseError));

                }

                #endregion

            }

            Thread.Sleep(2000);

        }

 

 

From: Rashid Abbas ***@***.***> 
Sent: Monday, January 29, 2024 8:20 AM
To: sflagp/QBXML-Object-Models ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sflagp/QBXML-Object-Models] Models are missing for ItemInventoryAssemblyQuery (Issue #5)

 

Hello Greg,

Seems some models are missing in the Library. I don't see any model to make the following query and handle the response.
https://developer.intuit.com/app/developer/qbdesktop/docs/api-reference/qbdesktop/iteminventoryassemblyquery

Would be a great help if you could implement and push the release.

Thank you

**Comment by sflagp** [comment]
Oh, I see it’s ItemInventoryAssembly (not ItemInventory). I will work on that tonight and have that out for you.

 

 

From: Rashid Abbas ***@***.***> 
Sent: Monday, January 29, 2024 8:20 AM
To: sflagp/QBXML-Object-Models ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sflagp/QBXML-Object-Models] Models are missing for ItemInventoryAssemblyQuery (Issue #5)

 

Hello Greg,

Seems some models are missing in the Library. I don't see any model to make the following query and handle the response.
https://developer.intuit.com/app/developer/qbdesktop/docs/api-reference/qbdesktop/iteminventoryassemblyquery

Would be a great help if you could implement and push the release.

Thank you

**Comment by sflagp** [comment]
The ItemInventoryAssembly is almost exactly the same as ItemInventory. The only difference I see is that it has BuildPoint instead of ReorderPoint.  Try this version and let me know if there are any errors. I haven't had a chance to test it so I'm not 100% sure that it will work.

[QbModels.1.2.8-beta01.zip](https://github.com/sflagp/QBXML-Object-Models/files/14085650/QbModels.1.2.8-beta01.zip)

**Comment by rashidabbas786** [comment]
Yes. they are pretty much similar. Without test is okay no worries <3

Thank you so much. <3
