### ISSUE TITLE
Missing Property for Model CustomerRetDto

### ISSUE THREAD

**Issue by rashidabbas786** [sflagp/QBXML-Object-Models#6]
Hello Greg,

Found a property that is missing inside CustomerRetDto Model.
Property name is: `TaxRegistrationNumber`

For Reference:
https://developer.intuit.com/app/developer/qbdesktop/docs/api-reference/qbdesktop/customerquery

**Comment by sflagp** [comment]
I see what happened. The TaxRegistrationNumber is only for Canadian and UK versions of QB. I added it into the dto.

[QbModels.1.2.8.zip](https://github.com/sflagp/QBXML-Object-Models/files/14087862/QbModels.1.2.8.zip)

**Comment by rashidabbas786** [comment]
Perfect. Thank You <3
