### ISSUE TITLE
MaxReturned not Parsed with ModifiedDate filters

### ISSUE THREAD

**Issue by rashi7863** [sflagp/QBXML-Object-Models#9]
Hello Greg,

I'm using QueryRq for the Models. I noticed that MaxReturned is not parsed to xml if we provide ModifiedDate etc or Name.

May I know the reference for this?

```
     [QbXmlOrder(200)]
    [XmlElement("MaxReturned")]
    public int? MaxReturned
    {
        get
        {
            if (ListID != null || FullName != null || ActiveStatus != null || FromModifiedDate.HasValue || ToModifiedDate.HasValue)
            {
                return null;
            }

            return maxReturned;
        }
        set
        {
            maxReturned = value;
        }
    }
    ```

**Comment by sflagp** [comment]
Off the top of my head, I cannot tell you why that is there. It is not in the documentation. However; when I removed that logic, one of my unit tests failed searching for a specific customer by list id. I get the following response:

QbProcessor error: -2147220480
QuickBooks found an error when parsing the provided XML text stream.

If I search by the same customer list id but also set the MaxReturned value to null, it works correctly. I think this has to do with the fact the I am setting the default MaxReturned value to 99999. I will have to research it some more.

Are you encountering any errors or issues with the MaxReturned query parameter?

Thanks

**Comment by sflagp** [comment]
Looking at the Unified Onscreen Reference, it seems that the MaxReturned cannot be combined with ListID nor FullName. However; ActiveStatus/FromModified/ToModified should be valid. This is only affecting List queries. Transaction queries are correct.

![image](https://github.com/sflagp/QBXML-Object-Models/assets/56395390/c0726942-e63b-4c06-90e6-df15be111062)

Please try this version and let me know if your query request are correct.
[QbModels.1.2.12-beta02.zip](https://github.com/sflagp/QBXML-Object-Models/files/14328978/QbModels.1.2.12-beta02.zip)

**Comment by rashi7863** [comment]
Perfect. Thank you Greg. <3
